automotive_social/accounts/urls.py
from django.urls import path
# because we dont want to mess the auth views with our views.py, we rename views as auth_views
from django.contrib.auth import views as auth_views
from . import views

# for url template used later ie: {% url 'accounts:login' %}
app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
			 name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('signup/', views.SignUp.as_view(), name='signup')

]

automotive_social/automotive_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('login_msg/', views.LoggedInPage.as_view(), name="login_msg"),
    path('logout_msg/', views.LoggedOutPage.as_view(), name="logout_msg"),
    path('', include("groups.urls", namespace="groups")),
    path('subgroups/', include("subgroups.urls", namespace="subgroups")),
    path('replies/', include("replies.urls", namespace="replies")),

]

automotive_social/groups/urls.py
from django.urls import path, include
from groups.views import ListGroups

app_name = "groups"

urlpatterns = [
	path('', ListGroups.as_view(), name='all'),
	# path('posts/', include("posts.urls", namespace="posts")),
    # path('subgroups/',include("subgroups.urls", namespace="subgroups")),

    # example 127.0.0.1:8000/audi
    # path('<slug>/', SingleGroup.as_view(), name='single'),


	# path("subgroups/in/<slug>/",views.SingleSubGroup.as_view(),name="single"),

]

automotive_social/subgroups/urls.py
from django.urls import path
from . import views

app_name = 'subgroups'

urlpatterns = [
	path('<slug>', views.ListSubGroups.as_view(), name='all'),
	path('create/', views.CreateSubGroup.as_view(), name='create'),
	path("<pk>/", views.ListSingleSubGroup.as_view(),name="replies"),
]

automotive_social/subgroups/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

# to connect a subgroup to an actual Group
from groups.models import Group

# slugify allows us to remove any characters that arent alphanumeric, underscores, or hyphens
from django.utils.text import slugify

# connect post to current user
from django.contrib.auth import get_user_model
User = get_user_model()

class SubGroup(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(allow_unicode=True, blank=True)
	description = models.TextField(blank=True, default='')
	created_at = models.DateTimeField(auto_now=True)
	


	user = models.ForeignKey(User, related_name='subgroups',on_delete=models.CASCADE)
	group = models.ForeignKey(Group, related_name='subgroups', null=True, blank=True,on_delete=models.CASCADE)


	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)


	# for the createview to redirect once form is submitted, 
	# redirects back to subgroup page you just created a new post on
	def get_absolute_url(self):
		return reverse('subgroups:all', kwargs={'slug':self.group.slug})


	class Meta:
		ordering = ['-created_at']

automotive_social/subgroups/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from subgroups.models import SubGroup
from groups.models import Group
from replies.models import Reply


from . import models

from django.contrib.auth import get_user_model
User = get_user_model()




# Create your views here.

# anyone logged in can create a subgroup
class CreateSubGroup(LoginRequiredMixin, generic.CreateView):
	# allowable fields to enter from SubGroup model
	fields = ('name', 'description')
	model = SubGroup

	# check if form is valid
	# This method is called when valid form data has been POSTed.
	def form_valid(self, form):
		# soft save, dont send to database yet
		self.object = form.save(commit=False)
		# we have a required username field
		# we need to connect this new post to the actual user itself at the request
		self.object.user = self.request.user
		# the primary key of the most recent group clicked was saved to the user's "first_name" field
		# save the pk we saved
		mypk = self.request.user.first_name
		# look for the name of the Group based off the primary key we saved
		name_of_group = Group.objects.get(pk=mypk)
		# we have a required group field
		# assign the name of group to the group field inside the form
		self.object.group = name_of_group
		# hard save the form to send info to the database
		self.object.save()
		return super().form_valid(form)




# auto looks for subgroup_list.html
class ListSubGroups(generic.ListView):

	model = SubGroup
	
	def get_context_data(self, **kwargs):
		
		context = super().get_context_data(**kwargs)

		# query through all subgroups, look for foreign keys where the slug is equal to slug of input
		# ie: click on 'audi', will look for subgroups tied with 'audi' foregin key
		# context related_subgroups will be used inside the url template of the subgroup_list.html page
		context['related_subgroups'] = SubGroup.objects.filter(group__slug=self.kwargs['slug'])

		context['this_group_name'] = SubGroup.objects.all().filter()




		
		'''
		Once the user clicks on a item in ListView, I want to save the primary key of that Group
		We'll later use that pk to fill in the group field when creating a new subgroup/ new post
		'''

		# save the request.path of the url
		# returns:  /subgroups/audi
		path_name = self.request.path

		# split the path name at the '/'
		# returns:  ['', 'subgroups', 'audi']
		path_name_split = path_name.split('/')

		# save the slug name used in the url path
		# returns:  audi 
		slug_from_url = path_name_split[-1]

		# filter through Group objects and look for the group where slug is equal to slug from url
		data_from_group = Group.objects.filter(slug=slug_from_url)

		# grab the primary key of the Group based off the slug input
		pk_to_send_to_user_model = data_from_group.get().pk

		# send the name of this current group to the subgroup_list.html as a context dictionary
		context['this_group_name'] = data_from_group.get().name    

		# add authenicated otherwise non logged in users will crash
		if self.request.user.is_authenticated:
			# this is the current active user logged in
			current_user = self.request.user

			# Grab the username inside User model based on the current active logged in user
			mypk = User.objects.get(username=current_user)

			# overwrite the default first_name field with the primary key of group that was clicked on
			mypk.first_name = pk_to_send_to_user_model

			# send to database the pk, we'll later use this pk to for creating new subgroups/creating new posts
			mypk.save()

		return context


# auto looks for subgroup_detail.html
# shows details about the subgroup, like posts inside the subgroup
class ListSingleSubGroup(generic.DetailView):
	model = SubGroup



	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)


		if self.request.user.is_authenticated:

			# save the pk of most recent subgroup clicked. pull this when creating reply
			# rigging to use last_name inside User model instead of creating new field

			current_user = self.request.user

			save_pk_of_subgroup_clicked = User.objects.get(username=current_user)

			save_pk_of_subgroup_clicked.last_name = self.object.pk

			print("this is self.object inside views py subgroups: {}".format(self.object))
			# print("this is self.object.group inside views py subgroups: {}".format(self.object.group))

			save_pk_of_subgroup_clicked.save()

		return context








automotive_social/subgroups/templates/subgroups/subgroup_base.html
{% extends 'base.html' %}
{% block content %}

	<div class='container'>
		<div class='row'>
			{% block pregroup %} {% endblock %}
			{% block group_content %} {% endblock %}
			{% block postgroup %} {% endblock %}	
		</div>
	</div>

{% endblock %}

automotive_social/subgroups/templates/subgroups/subgroup_detail.html
{% extends 'subgroups/subgroup_base.html' %}
{% block pregroup %}
	<div class="container" style="margin-top: 20px">
		<h1><strong>{{ subgroup.name }}</strong></h1>
		<h5><i><small>by {{subgroup.user}} on {{ subgroup.created_at }}</i></small></h5>
		<h1></h1>
		<h1></h1>

	</div>

{% endblock %}




{% block group_content %}

	<!-- <div class='container'> -->
	<div class="list-group-item list-group-item-action flex-column align-items-start" style="margin-bottom: 10px">
		{{ subgroup.description }}
		
	</div>	

	<div class='container'>
		{% if user.is_authenticated %}
			
			<a href="{% url 'replies:create' %}" class="btn btn-danger">Reply</a>

		{% else %}
			<a href="{% url 'accounts:signup' %}" class="btn btn-danger">Sign in to Reply</a>
			<a href="{% url 'accounts:login' %}" class="btn btn-danger">Log in to Reply</a>

		{% endif %}
			<h1><a href="{% url 'subgroups:all' slug=subgroup.group.slug %}" class="btn btn-primary">Back</a></h1>
			

	</div>



	<div class="col-md-8" style="margin-top: 50px">
		
	<h1></h1>

		{% if subgroup.replies_relatedname.count == 0 %}
			<h2>No post in this group yet</h2>
		{% else %}
			{% for each_reply in subgroup.replies_relatedname.all %}
				<h3>{{each_reply}}</h3>
				<h6><i><small>{{each_reply.user}}</i></small></h6>
				<h6><i><small>{{each_reply.created_at}}</i></small></h6>
				<h4>--------------</h4>

			{% endfor %}

		{% endif %}




	</div>




{% endblock %}

automotive_social/subgroups/templates/subgroups/subgroup_form.html
{% extends "subgroups/subgroup_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
<div class="container">
  <h4 style="margin-top: 20px">Create A New Post</h4>
  <form method="POST" action="{% url 'subgroups:create' %}" id="subGroupForm" style="margin-top: 20px">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-danger btn-large">Create</button>
  		<a href="{% url 'groups:all' %}" class="btn btn-primary">Home</a>
  	{% endbuttons %}


  </form>

</div>
{% endblock %}

automotive_social/subgroups/templates/subgroups/subgroup_list.html
{% extends "subgroups/subgroup_base.html" %}

{% block pregroup %}
<div style="margin-top: 20px" class="col-md-4">
	{% if user.is_authenticated %}
		<h3>Welcome Back</h3>
		<h3>@{{ user.username }}</h3>
		
	{% else %}
		<!-- <h3>Please <a href="#" class="btn btn-danger">Log In</a> or <a href="#" class="btn btn-danger">Sign Up</a> to Start a New Post  </h3> -->
		<h3>To Start a New Post</h3>
		<h3><a href="#" class="btn btn-danger">Log In</a> or <a href="#" class="btn btn-danger">Sign Up</a></h3>
	

	{% endif %}

	<a href="{% url 'groups:all' %}" class="btn btn-primary" style="margin-top: 10px">Back to Home Page</a>

</div>
{% endblock %}

{% block group_content %}

<div class="col-md-8">
	<div class="list-group">
		<h1 style="text-align: center; margin-top: 20px"><strong>{{ this_group_name }}</strong></h4>

		{% if user.is_authenticated %}

			<a href="{% url 'subgroups:create' %}" class="btn btn-danger" style="margin-top: 10px">Create New Post</a>

		{% endif %}

		<h4 style="margin-top: 10px">{{ group.name }}</h4>	

		{% for item in related_subgroups %}
		<div class="list-group-item list-group-item-action flex-column align-items-start" style="color: #4185FB">


			<a href="{% url 'subgroups:replies' pk=item.pk %}" >

				<h4>{{ item }}</h4>
				<!-- <h4>{{ item.pk }}</h4> -->
			</a>

			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted">
					Created by {{ item.user }}
				</small>
				<small class="text-muted">
					Created on {{ item.created_at }}
				</small>
				<span></span><span></span>
			</div>

		</div>
			




		{% endfor %}



	</div>

</div>
{% endblock %}


<!-- <a href="{% url 'subgroups:replies' %}"> -->


		<a href="{% url 'subgroups:replies' pk=item.pk slug=item.slug %}">
	