automotive_social/accounts/urls.py
from django.urls import path
# because we dont want to mess the auth views with our views.py, we rename views as auth_views
from django.contrib.auth import views as auth_views
from . import views

# for url template used later ie: {% url 'accounts:login' %}
app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
			 name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('signup/', views.SignUp.as_view(), name='signup')

]

automotive_social/automotive_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('login_msg/', views.LoggedInPage.as_view(), name="login_msg"),
    path('logout_msg/', views.LoggedOutPage.as_view(), name="logout_msg"),
    path('', include("groups.urls", namespace="groups")),
    path('subgroups/', include("subgroups.urls", namespace="subgroups")),
    path('replies/', include("replies.urls", namespace="replies")),

]

automotive_social/groups/urls.py
from django.urls import path, include
from groups.views import ListGroups

app_name = "groups"

urlpatterns = [
	path('', ListGroups.as_view(), name='all'),
	# path('posts/', include("posts.urls", namespace="posts")),
    # path('subgroups/',include("subgroups.urls", namespace="subgroups")),

    # example 127.0.0.1:8000/audi
    # path('<slug>/', SingleGroup.as_view(), name='single'),


	# path("subgroups/in/<slug>/",views.SingleSubGroup.as_view(),name="single"),

]

automotive_social/groups/models.py
from django.db import models
# slugify allows us to remove any characters that arent alphanumeric, underscores, or hyphens
from django.utils.text import slugify
# returns the user model that is currently active in this project
from django.contrib.auth import get_user_model
User = get_user_model()

from django.urls import reverse



class Group(models.Model):
	name = models.CharField(max_length=50, unique=True)
	slug = models.SlugField(allow_unicode=True, unique=True, blank=True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	# def get_absolute_url(self):
	# 	return reverse('groups:single', kwargs={'slug':self.slug})

	class Meta:
		ordering = ['name']

automotive_social/groups/views.py
from django.shortcuts import render
from django.views import generic
from groups.models import Group
# from . import models


class ListGroups(generic.ListView):
	# automatically looks for a group_list.html
	model = Group


automotive_social/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

	<div class='container'>
		<div class='row'>
			{% block pregroup %} {% endblock %}
			{% block group_content %} {% endblock %}
		</div>
	</div>

{% endblock %}

automotive_social/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div style="margin-top: 20px" class="col-md-4">
	<!-- <div class="content">
		<p></p>
		<h1>Welcome to Automotive Social</h1>
	</div>
 -->
	{% if user.is_authenticated %}
		<h3>Welcome Back to Automotive Social @{{ user.username }}</h3>
		
	{% else %}
		<!-- <h3>Please <a href="#" class="btn btn-danger">Log In</a> or <a href="#" class="btn btn-danger">Sign Up</a> to Start a New Post  </h3> -->
		<h3>Welcome to Automotive Social</h3>
		<h3>To Start a New Post</h3>
		<h3><a href="{% url 'accounts:login' %}" class="btn btn-danger">Log In</a> or <a href="{% url 'accounts:signup' %}" class="btn btn-danger">Sign Up</a></h3>
	
	{% endif %}



</div>
{% endblock %}

{% block group_content %}

<div class="col-md-8">

	<div class="list-group" style="margin-top: 20px">

		{% for group in object_list %}
		<!-- "{% url 'subgroups:all' slug=group.slug %}" -->
		<a href="{% url 'subgroups:all' slug=group.slug %}" class="list-group-item list-group-item-action flex-column align-items-start" style="color: #4185FB">
			<h3>{{ group.name }}</h3>
<!-- 			<h5>slug {{ group.slug }}</h5>
			<h5>pk {{ group.pk }}</h5> -->
			
		</a>

		

		{% endfor %}
	</div><!-- 
</div> -->
{% endblock %}


<!-- 
		<a href="{% url 'groups:all' slug=group.name %}">
			<h3 class="mb-1">{{ group.name }}</h3>
		</a> -->