automotive_social/accounts/urls.py
from django.urls import path
# because we dont want to mess the auth views with our views.py, we rename views as auth_views
from django.contrib.auth import views as auth_views
from . import views

# for url template used later ie: {% url 'accounts:login' %}
app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
			 name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('signup/', views.SignUp.as_view(), name='signup')

]

automotive_social/automotive_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('login_msg/', views.LoggedInPage.as_view(), name="login_msg"),
    path('logout_msg/', views.LoggedOutPage.as_view(), name="logout_msg"),
    path('', include("groups.urls", namespace="groups")),
    path('subgroups/', include("subgroups.urls", namespace="subgroups")),
    path('replies/', include("replies.urls", namespace="replies")),

]

automotive_social/groups/urls.py
from django.urls import path, include
from groups.views import ListGroups

app_name = "groups"

urlpatterns = [
	path('', ListGroups.as_view(), name='all'),
	# path('posts/', include("posts.urls", namespace="posts")),
    # path('subgroups/',include("subgroups.urls", namespace="subgroups")),

    # example 127.0.0.1:8000/audi
    # path('<slug>/', SingleGroup.as_view(), name='single'),


	# path("subgroups/in/<slug>/",views.SingleSubGroup.as_view(),name="single"),

]

automotive_social/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Automotive Social</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'groups:all' %}">Automotive Social</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <script src="{% static 'simplesocial/js/master.js' %}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

automotive_social/templates/index.html
{% extends 'base.html' %}

{% block content %}
this is home page


<h1>Welcome to automotive Social</h1>


{% endblock %}

automotive_social/templates/login_msg.html
{% extends 'base.html' %}


{% block content %}

<div class="container" style="margin-top: 20px">
	<h1>You have successfully logged in!</h1>
	<h1><a href="{% url 'groups:all' %}" class="btn btn-primary">Home Page</a></h1>


</div>


{% endblock %}

automotive_social/templates/logout_msg.html
{% extends 'base.html' %}


{% block content %}

<div class="container" style="margin-top: 20px">
  <h1>You have logged out!</h1>
  <h1><a href="{% url 'groups:all' %}" class="btn btn-primary">Home Page</a></h1>

</div>

{% endblock %}